console.log("products.js loading...");

// Direct Unsplash URLs — each mapped to a real PC-part photo
const IMG = {
  // GPUs
  gpu_nvidia:   "https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800&h=800&fit=crop&auto=format&q=85",
  gpu_amd:      "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=800&h=800&fit=crop&auto=format&q=85",
  gpu_green:    "https://images.unsplash.com/photo-1625842268584-8f3296236761?w=800&h=800&fit=crop&auto=format&q=85",
  gpu_red:      "https://images.unsplash.com/photo-1640955014216-75201056c829?w=800&h=800&fit=crop&auto=format&q=85",
  gpu_generic:  "https://images.unsplash.com/photo-1555617981-dac3880eac6e?w=800&h=800&fit=crop&auto=format&q=85",
  // CPUs
  cpu_amd:      "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&h=800&fit=crop&auto=format&q=85",
  cpu_intel:    "https://images.unsplash.com/photo-1555617981-dac3880eac6e?w=800&h=800&fit=crop&auto=format&q=85",
  cpu_chip:     "https://images.unsplash.com/photo-1601132359864-c974e79890ac?w=800&h=800&fit=crop&auto=format&q=85",
  // Motherboards
  mb_asus:      "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&h=800&fit=crop&auto=format&q=85",
  mb_msi:       "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&h=800&fit=crop&auto=format&q=85",
  mb_gigabyte:  "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=800&fit=crop&auto=format&q=85",
  mb_generic:   "https://images.unsplash.com/photo-1562976540-1502c2145186?w=800&h=800&fit=crop&auto=format&q=85",
  // RAM
  ram_rgb:      "https://images.unsplash.com/photo-1562976540-1502c2145186?w=800&h=800&fit=crop&auto=format&q=85",
  ram_plain:    "https://images.unsplash.com/photo-1541029071515-84cc54f84dc5?w=800&h=800&fit=crop&auto=format&q=85",
  ram_corsair:  "https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=800&h=800&fit=crop&auto=format&q=85",
  // Storage — NVMe SSD
  ssd_nvme:     "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&h=800&fit=crop&auto=format&q=85",
  ssd_sata:     "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=800&fit=crop&auto=format&q=85",
  hdd:          "https://images.unsplash.com/photo-1531492746076-161ca9bcad58?w=800&h=800&fit=crop&auto=format&q=85",
  // PSU
  psu:          "https://images.unsplash.com/photo-1587202372583-49330a15584d?w=800&h=800&fit=crop&auto=format&q=85",
  // Cases
  case_glass:   "https://images.unsplash.com/photo-1587202372616-b43abea06c2a?w=800&h=800&fit=crop&auto=format&q=85",
  case_mesh:    "https://images.unsplash.com/photo-1593640408182-31c70c8268f5?w=800&h=800&fit=crop&auto=format&q=85",
  case_rgb:     "https://images.unsplash.com/photo-1616588589676-62b3bd4ff6d2?w=800&h=800&fit=crop&auto=format&q=85",
  // Cooling
  cool_aio:     "https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=800&h=800&fit=crop&auto=format&q=85",
  cool_air:     "https://images.unsplash.com/photo-1555617981-dac3880eac6e?w=800&h=800&fit=crop&auto=format&q=85",
  cool_fan:     "https://images.unsplash.com/photo-1541029071515-84cc54f84dc5?w=800&h=800&fit=crop&auto=format&q=85",
};

export const PARTVAULT_PRODUCTS = [
  // ─── GPUs ────────────────────────────────────────────────────────────────────
  {
    id: "gpu-5070ti",
    name: "GeForce RTX 5070 Ti 16GB",
    brand: "NVIDIA",
    category: "GPU",
    price: 40900,
    was: 49900,
    image: IMG.gpu_nvidia,
    rating: 4.8,
    specs: ["16GB GDDR7", "DLSS 4", "PCIe 5.0", "320W TGP"],
    stock: "in",
    isNew: true,
  },
  {
    id: "gpu-7900xtx",
    name: "Radeon RX 7900 XTX 24GB",
    brand: "AMD",
    category: "GPU",
    price: 52200,
    was: null,
    image: IMG.gpu_amd,
    rating: 4.7,
    specs: ["24GB GDDR6", "RDNA 3", "DisplayPort 2.1"],
    stock: "in",
    isNew: false,
  },
  {
    id: "gpu-4060",
    name: "GeForce RTX 4060 8GB",
    brand: "MSI",
    category: "GPU",
    price: 17400,
    was: 19100,
    image: IMG.gpu_green,
    rating: 4.5,
    specs: ["8GB GDDR6", "Twin Frozr", "115W"],
    stock: "in",
    isNew: false,
  },
  {
    id: "gpu-5080",
    name: "GeForce RTX 5080 16GB",
    brand: "GIGABYTE",
    category: "GPU",
    price: 58000,
    was: null,
    image: IMG.gpu_nvidia,
    rating: 4.7,
    specs: ["Windforce cooling", "16GB GDDR7", "RGB"],
    stock: "low",
    isNew: true,
  },
  {
    id: "gpu-4070super",
    name: "GeForce RTX 4070 SUPER 12GB",
    brand: "ASUS",
    category: "GPU",
    price: 33600,
    was: 36500,
    image: IMG.gpu_amd,
    rating: 4.7,
    specs: ["12GB GDDR6X", "DLSS 3.5", "PCIe 4.0"],
    stock: "in",
    isNew: false,
  },
  {
    id: "gpu-7800xt",
    name: "Radeon RX 7800 XT 16GB",
    brand: "Sapphire",
    category: "GPU",
    price: 28900,
    was: null,
    image: IMG.gpu_green,
    rating: 4.6,
    specs: ["16GB GDDR6", "RDNA 3", "DisplayPort 2.1"],
    stock: "in",
    isNew: false,
  },
  {
    id: "gpu-3090ti",
    name: "GeForce RTX 3090 Ti 24GB",
    brand: "MSI",
    category: "GPU",
    price: 58000,
    was: 69600,
    image: IMG.gpu_red,
    rating: 4.5,
    specs: ["24GB GDDR6X", "PCIe 4.0", "450W TGP"],
    stock: "low",
    isNew: false,
  },
  {
    id: "gpu-4080super",
    name: "GeForce RTX 4080 SUPER 16GB",
    brand: "ASUS",
    category: "GPU",
    price: 52200,
    was: 58000,
    image: IMG.gpu_nvidia,
    rating: 4.8,
    specs: ["16GB GDDR6X", "DLSS 3.5", "PCIe 4.0"],
    stock: "in",
    isNew: false,
  },
  {
    id: "gpu-4060ti",
    name: "GeForce RTX 4060 Ti 16GB",
    brand: "ZOTAC",
    category: "GPU",
    price: 24900,
    was: null,
    image: IMG.gpu_amd,
    rating: 4.4,
    specs: ["16GB GDDR6", "DLSS 3", "PCIe 4.0"],
    stock: "in",
    isNew: false,
  },
  {
    id: "gpu-7600",
    name: "Radeon RX 7600 8GB",
    brand: "PowerColor",
    category: "GPU",
    price: 14500,
    was: 16200,
    image: IMG.gpu_green,
    rating: 4.2,
    specs: ["8GB GDDR6", "RDNA 3", "1080p gaming"],
    stock: "in",
    isNew: false,
  },
  {
    id: "gpu-7700xt",
    name: "Radeon RX 7700 XT 12GB",
    brand: "Sapphire",
    category: "GPU",
    price: 24900,
    was: null,
    image: IMG.gpu_red,
    rating: 4.5,
    specs: ["12GB GDDR6", "AV1 encode", "RDNA 3"],
    stock: "in",
    isNew: false,
  },
  {
    id: "gpu-a770",
    name: "Arc A770 16GB",
    brand: "Intel",
    category: "GPU",
    price: 17400,
    was: 20300,
    image: IMG.gpu_nvidia,
    rating: 4.1,
    specs: ["16GB GDDR6", "XeSS", "PCIe 4.0"],
    stock: "in",
    isNew: false,
  },
  {
    id: "gpu-6750xt",
    name: "Radeon RX 6750 XT 12GB",
    brand: "XFX",
    category: "GPU",
    price: 18500,
    was: null,
    image: IMG.gpu_amd,
    rating: 4.4,
    specs: ["12GB GDDR6", "RDNA 2", "1440p ready"],
    stock: "in",
    isNew: false,
  },
  {
    id: "gpu-3060",
    name: "GeForce RTX 3060 12GB",
    brand: "GIGABYTE",
    category: "GPU",
    price: 16200,
    was: 19100,
    image: IMG.gpu_green,
    rating: 4.3,
    specs: ["12GB GDDR6", "DLSS 2", "PCIe 4.0"],
    stock: "in",
    isNew: false,
  },
  {
    id: "gpu-5090",
    name: "GeForce RTX 5090 32GB",
    brand: "NVIDIA",
    category: "GPU",
    price: 116000,
    was: null,
    image: IMG.gpu_nvidia,
    rating: 4.9,
    specs: ["32GB GDDR7", "DLSS 4", "PCIe 5.0", "575W TGP"],
    stock: "low",
    isNew: true,
  },
  {
    id: "gpu-7900gre",
    name: "Radeon RX 7900 GRE 16GB",
    brand: "AMD",
    category: "GPU",
    price: 29000,
    was: 34800,
    image: IMG.gpu_red,
    rating: 4.6,
    specs: ["16GB GDDR6", "RDNA 3", "PCIe 4.0"],
    stock: "in",
    isNew: false,
  },
  {
    id: "gpu-4070ti",
    name: "GeForce RTX 4070 Ti 12GB",
    brand: "MSI",
    category: "GPU",
    price: 40600,
    was: 46400,
    image: IMG.gpu_amd,
    rating: 4.6,
    specs: ["12GB GDDR6X", "DLSS 3", "PCIe 4.0"],
    stock: "in",
    isNew: false,
  },
  {
    id: "gpu-6800xt",
    name: "Radeon RX 6800 XT 16GB",
    brand: "Sapphire",
    category: "GPU",
    price: 23200,
    was: null,
    image: IMG.gpu_green,
    rating: 4.4,
    specs: ["16GB GDDR6", "RDNA 2", "PCIe 4.0"],
    stock: "low",
    isNew: false,
  },
  {
    id: "gpu-4090",
    name: "GeForce RTX 4090 24GB",
    brand: "ASUS",
    category: "GPU",
    price: 87000,
    was: 101500,
    image: IMG.gpu_nvidia,
    rating: 4.9,
    specs: ["24GB GDDR6X", "DLSS 3", "PCIe 4.0", "450W TGP"],
    stock: "in",
    isNew: false,
  },
  {
    id: "gpu-7650xt",
    name: "Radeon RX 7650 XT 8GB",
    brand: "PowerColor",
    category: "GPU",
    price: 16800,
    was: null,
    image: IMG.gpu_red,
    rating: 4.3,
    specs: ["8GB GDDR6", "RDNA 3.5", "PCIe 4.0"],
    stock: "in",
    isNew: true,
  },

  // ─── CPUs ────────────────────────────────────────────────────────────────────
  {
    id: "cpu-9800x3d",
    name: "Ryzen 7 9800X3D",
    brand: "AMD",
    category: "CPU",
    price: 27800,
    was: null,
    image: IMG.cpu_amd,
    rating: 4.9,
    specs: ["8C/16T", "96MB 3D V-Cache", "AM5", "120W"],
    stock: "in",
    isNew: false,
  },
  {
    id: "cpu-14700k",
    name: "Core i7-14700K",
    brand: "Intel",
    category: "CPU",
    price: 22000,
    was: 24300,
    image: IMG.cpu_intel,
    rating: 4.6,
    specs: ["20 cores (8P+12E)", "LGA1700", "125W"],
    stock: "in",
    isNew: false,
  },
  {
    id: "cpu-7700",
    name: "Ryzen 7 7700",
    brand: "AMD",
    category: "CPU",
    price: 16200,
    was: null,
    image: IMG.cpu_amd,
    rating: 4.4,
    specs: ["8C/16T", "AM5", "65W"],
    stock: "in",
    isNew: false,
  },
  {
    id: "cpu-14600k",
    name: "Core i5-14600K",
    brand: "Intel",
    category: "CPU",
    price: 16800,
    was: 18500,
    image: IMG.cpu_intel,
    rating: 4.7,
    specs: ["14 cores (6P+8E)", "LGA1700", "125W"],
    stock: "in",
    isNew: false,
  },
  {
    id: "cpu-7600x",
    name: "Ryzen 5 7600X",
    brand: "AMD",
    category: "CPU",
    price: 12700,
    was: null,
    image: IMG.cpu_amd,
    rating: 4.5,
    specs: ["6C/12T", "AM5", "105W"],
    stock: "in",
    isNew: false,
  },
  {
    id: "cpu-14900k",
    name: "Core i9-14900K",
    brand: "Intel",
    category: "CPU",
    price: 31900,
    was: 34800,
    image: IMG.cpu_chip,
    rating: 4.8,
    specs: ["24 cores", "LGA1700", "125W base"],
    stock: "in",
    isNew: false,
  },
  {
    id: "cpu-13900k",
    name: "Core i9-13900K",
    brand: "Intel",
    category: "CPU",
    price: 27200,
    was: null,
    image: IMG.cpu_chip,
    rating: 4.7,
    specs: ["24 cores", "LGA1700", "125W base"],
    stock: "in",
    isNew: false,
  },
  {
    id: "cpu-12700k",
    name: "Core i7-12700K",
    brand: "Intel",
    category: "CPU",
    price: 14500,
    was: 17400,
    image: IMG.cpu_intel,
    rating: 4.5,
    specs: ["12 cores", "LGA1700", "Unlocked"],
    stock: "in",
    isNew: false,
  },
  {
    id: "cpu-13400f",
    name: "Core i5-13400F",
    brand: "Intel",
    category: "CPU",
    price: 11000,
    was: null,
    image: IMG.cpu_intel,
    rating: 4.4,
    specs: ["10 cores", "No iGPU", "LGA1700"],
    stock: "in",
    isNew: false,
  },
  {
    id: "cpu-7950x",
    name: "Ryzen 9 7950X",
    brand: "AMD",
    category: "CPU",
    price: 29000,
    was: 34800,
    image: IMG.cpu_amd,
    rating: 4.8,
    specs: ["16C/32T", "AM5", "170W"],
    stock: "in",
    isNew: false,
  },
  {
    id: "cpu-7900",
    name: "Ryzen 9 7900",
    brand: "AMD",
    category: "CPU",
    price: 20300,
    was: null,
    image: IMG.cpu_amd,
    rating: 4.6,
    specs: ["12C/24T", "AM5", "65W"],
    stock: "in",
    isNew: false,
  },
  {
    id: "cpu-5700x",
    name: "Ryzen 7 5700X",
    brand: "AMD",
    category: "CPU",
    price: 9800,
    was: 11600,
    image: IMG.cpu_chip,
    rating: 4.5,
    specs: ["8C/16T", "AM4", "65W"],
    stock: "in",
    isNew: false,
  },
  {
    id: "cpu-9950x",
    name: "Ryzen 9 9950X",
    brand: "AMD",
    category: "CPU",
    price: 40600,
    was: null,
    image: IMG.cpu_amd,
    rating: 4.9,
    specs: ["16C/32T", "AM5", "170W", "Zen 5"],
    stock: "low",
    isNew: true,
  },
  {
    id: "cpu-ultra9",
    name: "Core Ultra 9 285K",
    brand: "Intel",
    category: "CPU",
    price: 34800,
    was: 40600,
    image: IMG.cpu_chip,
    rating: 4.8,
    specs: ["24 cores", "LGA1851", "125W"],
    stock: "in",
    isNew: true,
  },
  {
    id: "cpu-ultra5",
    name: "Core Ultra 5 245K",
    brand: "Intel",
    category: "CPU",
    price: 20300,
    was: null,
    image: IMG.cpu_intel,
    rating: 4.6,
    specs: ["14 cores", "LGA1851", "125W"],
    stock: "in",
    isNew: true,
  },
  {
    id: "cpu-7800x3d",
    name: "Ryzen 7 7800X3D",
    brand: "AMD",
    category: "CPU",
    price: 23200,
    was: 27800,
    image: IMG.cpu_amd,
    rating: 4.9,
    specs: ["8C/16T", "96MB 3D V-Cache", "AM5", "120W"],
    stock: "in",
    isNew: false,
  },
  {
    id: "cpu-5600x",
    name: "Ryzen 5 5600X",
    brand: "AMD",
    category: "CPU",
    price: 8700,
    was: 11600,
    image: IMG.cpu_chip,
    rating: 4.7,
    specs: ["6C/12T", "AM4", "65W"],
    stock: "in",
    isNew: false,
  },
  {
    id: "cpu-13600k",
    name: "Core i5-13600K",
    brand: "Intel",
    category: "CPU",
    price: 17400,
    was: 20300,
    image: IMG.cpu_intel,
    rating: 4.7,
    specs: ["14 cores", "LGA1700", "125W"],
    stock: "in",
    isNew: false,
  },
  {
    id: "cpu-9700x",
    name: "Ryzen 7 9700X",
    brand: "AMD",
    category: "CPU",
    price: 23200,
    was: null,
    image: IMG.cpu_amd,
    rating: 4.7,
    specs: ["8C/16T", "AM5", "65W", "Zen 5"],
    stock: "in",
    isNew: true,
  },
  {
    id: "cpu-14400f",
    name: "Core i5-14400F",
    brand: "Intel",
    category: "CPU",
    price: 10200,
    was: 12700,
    image: IMG.cpu_intel,
    rating: 4.4,
    specs: ["10 cores", "No iGPU", "LGA1700"],
    stock: "in",
    isNew: false,
  },

  // ─── Motherboards ─────────────────────────────────────────────────────────────
  {
    id: "mb-x670e",
    name: "ROG Crosshair X670E Hero",
    brand: "ASUS",
    category: "Motherboard",
    price: 37700,
    was: null,
    image: IMG.mb_asus,
    rating: 4.7,
    specs: ["AM5", "DDR5", "PCIe 5.0", "WiFi 7"],
    stock: "in",
    isNew: false,
  },
  {
    id: "mb-b650",
    name: "MAG B650 Tomahawk WiFi",
    brand: "MSI",
    category: "Motherboard",
    price: 11000,
    was: 12100,
    image: IMG.mb_msi,
    rating: 4.6,
    specs: ["AM5", "DDR5", "2.5G LAN"],
    stock: "in",
    isNew: false,
  },
  {
    id: "mb-z790",
    name: "TUF Gaming Z790-Plus WiFi",
    brand: "ASUS",
    category: "Motherboard",
    price: 13300,
    was: null,
    image: IMG.mb_gigabyte,
    rating: 4.5,
    specs: ["LGA1700", "DDR5", "PCIe 5.0"],
    stock: "in",
    isNew: false,
  },
  {
    id: "mb-b760m",
    name: "B760M AORUS Elite AX",
    brand: "GIGABYTE",
    category: "Motherboard",
    price: 9200,
    was: null,
    image: IMG.mb_asus,
    rating: 4.4,
    specs: ["LGA1700", "DDR5", "WiFi 6E"],
    stock: "in",
    isNew: false,
  },
  {
    id: "mb-a620m",
    name: "Prime A620M-A WiFi",
    brand: "ASUS",
    category: "Motherboard",
    price: 6900,
    was: 7500,
    image: IMG.mb_msi,
    rating: 4.3,
    specs: ["AM5", "DDR5", "mATX"],
    stock: "in",
    isNew: false,
  },
  {
    id: "mb-x870e",
    name: "X870E AORUS Master",
    brand: "GIGABYTE",
    category: "Motherboard",
    price: 29000,
    was: null,
    image: IMG.mb_gigabyte,
    rating: 4.8,
    specs: ["AM5", "PCIe 5.0", "WiFi 7"],
    stock: "in",
    isNew: true,
  },
  {
    id: "mb-b650e",
    name: "B650E Steel Legend WiFi",
    brand: "ASRock",
    category: "Motherboard",
    price: 12700,
    was: 13900,
    image: IMG.mb_asus,
    rating: 4.5,
    specs: ["AM5", "DDR5", "PCIe 5.0 x16"],
    stock: "in",
    isNew: false,
  },
  {
    id: "mb-z690",
    name: "Z690 Gaming X DDR4",
    brand: "GIGABYTE",
    category: "Motherboard",
    price: 9800,
    was: null,
    image: IMG.mb_msi,
    rating: 4.3,
    specs: ["LGA1700", "DDR4", "ATX"],
    stock: "in",
    isNew: false,
  },
  {
    id: "mb-b550",
    name: "B550 Tomahawk Max WiFi",
    brand: "MSI",
    category: "Motherboard",
    price: 8700,
    was: 9800,
    image: IMG.mb_gigabyte,
    rating: 4.6,
    specs: ["AM4", "PCIe 4.0", "2.5G LAN"],
    stock: "in",
    isNew: false,
  },
  {
    id: "mb-h610m",
    name: "H610M-E D4",
    brand: "ASUS",
    category: "Motherboard",
    price: 5200,
    was: null,
    image: IMG.mb_asus,
    rating: 4.1,
    specs: ["LGA1700", "DDR4", "mATX"],
    stock: "in",
    isNew: false,
  },
  {
    id: "mb-z790-aero",
    name: "Z790 AERO G",
    brand: "GIGABYTE",
    category: "Motherboard",
    price: 16800,
    was: null,
    image: IMG.mb_msi,
    rating: 4.6,
    specs: ["LGA1700", "DDR5", "Creator-focused I/O"],
    stock: "in",
    isNew: false,
  },
  {
    id: "mb-x670-p",
    name: "Pro X670-P WiFi",
    brand: "MSI",
    category: "Motherboard",
    price: 12100,
    was: 13300,
    image: IMG.mb_gigabyte,
    rating: 4.4,
    specs: ["AM5", "DDR5", "ATX"],
    stock: "in",
    isNew: false,
  },
  {
    id: "mb-b850",
    name: "MAG B850 Tomahawk WiFi",
    brand: "MSI",
    category: "Motherboard",
    price: 14500,
    was: null,
    image: IMG.mb_asus,
    rating: 4.7,
    specs: ["AM5", "DDR5", "PCIe 5.0", "WiFi 7"],
    stock: "in",
    isNew: true,
  },
  {
    id: "mb-z890",
    name: "ROG Maximus Z890 Apex",
    brand: "ASUS",
    category: "Motherboard",
    price: 52200,
    was: null,
    image: IMG.mb_msi,
    rating: 4.8,
    specs: ["LGA1851", "DDR5", "PCIe 5.0", "WiFi 7"],
    stock: "low",
    isNew: true,
  },
  {
    id: "mb-b760",
    name: "B760 Gaming X AX",
    brand: "GIGABYTE",
    category: "Motherboard",
    price: 10400,
    was: 11600,
    image: IMG.mb_gigabyte,
    rating: 4.5,
    specs: ["LGA1700", "DDR5", "WiFi 6E"],
    stock: "in",
    isNew: false,
  },

  // ─── RAM ─────────────────────────────────────────────────────────────────────
  {
    id: "ram-32-ddr5",
    name: "Vengeance RGB 32GB (2x16) DDR5-6000",
    brand: "Corsair",
    category: "RAM",
    price: 6900,
    was: 8100,
    image: IMG.ram_rgb,
    rating: 4.8,
    specs: ["CL30", "EXPO + XMP", "RGB"],
    stock: "in",
    isNew: false,
  },
  {
    id: "ram-64-ddr5",
    name: "Trident Z5 RGB 64GB (2x32) DDR5-5600",
    brand: "G.Skill",
    category: "RAM",
    price: 12700,
    was: null,
    image: IMG.ram_plain,
    rating: 4.7,
    specs: ["CL40", "Intel XMP 3.0"],
    stock: "in",
    isNew: false,
  },
  {
    id: "ram-32-ddr4",
    name: "Ripjaws V 32GB (2x16) DDR4-3600",
    brand: "G.Skill",
    category: "RAM",
    price: 4300,
    was: 5200,
    image: IMG.ram_rgb,
    rating: 4.6,
    specs: ["CL18", "XMP", "DDR4"],
    stock: "in",
    isNew: false,
  },
  {
    id: "ram-96-ddr5",
    name: "Dominator Titanium 96GB (2x48) DDR5-6400",
    brand: "Corsair",
    category: "RAM",
    price: 23200,
    was: null,
    image: IMG.ram_corsair,
    rating: 4.8,
    specs: ["CL32", "XMP 3.0", "RGB"],
    stock: "in",
    isNew: false,
  },
  {
    id: "ram-16-ddr5",
    name: "Fury Beast 16GB (2x8) DDR5-5600",
    brand: "Kingston",
    category: "RAM",
    price: 4000,
    was: 4600,
    image: IMG.ram_rgb,
    rating: 4.3,
    specs: ["CL36", "XMP", "Low-profile"],
    stock: "in",
    isNew: false,
  },
  {
    id: "ram-64-ddr4",
    name: "Vengeance LPX 64GB (2x32) DDR4-3200",
    brand: "Corsair",
    category: "RAM",
    price: 8100,
    was: null,
    image: IMG.ram_plain,
    rating: 4.7,
    specs: ["CL16", "XMP 2.0", "DDR4"],
    stock: "in",
    isNew: false,
  },
  {
    id: "ram-48-ddr5",
    name: "Trident Z5 Neo 48GB (2x24) DDR5-6000",
    brand: "G.Skill",
    category: "RAM",
    price: 9800,
    was: 11000,
    image: IMG.ram_rgb,
    rating: 4.6,
    specs: ["CL30", "EXPO", "RGB"],
    stock: "in",
    isNew: false,
  },
  {
    id: "ram-32-ddr5-5600",
    name: "Kingston Fury 32GB (2x16) DDR5-5600",
    brand: "Kingston",
    category: "RAM",
    price: 5800,
    was: null,
    image: IMG.ram_plain,
    rating: 4.4,
    specs: ["CL36", "XMP", "DDR5"],
    stock: "in",
    isNew: false,
  },
  {
    id: "ram-128-ddr5",
    name: "Vengeance 128GB (4x32) DDR5-5200",
    brand: "Corsair",
    category: "RAM",
    price: 25500,
    was: null,
    image: IMG.ram_rgb,
    rating: 4.7,
    specs: ["CL40", "Workstation kit", "DDR5"],
    stock: "in",
    isNew: false,
  },
  {
    id: "ram-16-ddr4",
    name: "TeamGroup T-Force Vulcan Z 16GB DDR4-3200",
    brand: "TeamGroup",
    category: "RAM",
    price: 2300,
    was: 2900,
    image: IMG.ram_plain,
    rating: 4.2,
    specs: ["CL16", "Single kit", "DDR4"],
    stock: "in",
    isNew: false,
  },
  {
    id: "ram-32-ddr5-7200",
    name: "Trident Z5 RGB 32GB DDR5-7200",
    brand: "G.Skill",
    category: "RAM",
    price: 11600,
    was: null,
    image: IMG.ram_rgb,
    rating: 4.8,
    specs: ["CL34", "XMP 3.0", "RGB"],
    stock: "low",
    isNew: true,
  },
  {
    id: "ram-64-ddr5-6400",
    name: "Dominator Platinum 64GB DDR5-6400",
    brand: "Corsair",
    category: "RAM",
    price: 20300,
    was: 23200,
    image: IMG.ram_corsair,
    rating: 4.7,
    specs: ["CL32", "RGB", "XMP 3.0"],
    stock: "in",
    isNew: false,
  },
  {
    id: "ram-32-expo",
    name: "Fury Beast 32GB DDR5-6000 EXPO",
    brand: "Kingston",
    category: "RAM",
    price: 6400,
    was: null,
    image: IMG.ram_rgb,
    rating: 4.5,
    specs: ["CL36", "EXPO", "AMD optimized"],
    stock: "in",
    isNew: true,
  },
  {
    id: "ram-16-lp",
    name: "Lancer Blade 16GB DDR5-5600",
    brand: "TeamGroup",
    category: "RAM",
    price: 3500,
    was: 4000,
    image: IMG.ram_plain,
    rating: 4.3,
    specs: ["CL36", "Low-profile", "DDR5"],
    stock: "in",
    isNew: false,
  },
  {
    id: "ram-256-ddr5",
    name: "Vengeance 256GB (8x32) DDR5-4800",
    brand: "Corsair",
    category: "RAM",
    price: 52200,
    was: null,
    image: IMG.ram_corsair,
    rating: 4.6,
    specs: ["CL40", "HEDT kit", "DDR5"],
    stock: "out",
    isNew: false,
  },

  // ─── Storage ──────────────────────────────────────────────────────────────────
  {
    id: "ssd-990pro",
    name: "990 PRO 2TB NVMe SSD",
    brand: "Samsung",
    category: "Storage",
    price: 10400,
    was: 11600,
    image: IMG.ssd_nvme,
    rating: 4.9,
    specs: ["PCIe 4.0", "7450 MB/s read", "M.2 2280"],
    stock: "in",
    isNew: false,
  },
  {
    id: "ssd-sn850x",
    name: "WD Black SN850X 4TB",
    brand: "Western Digital",
    category: "Storage",
    price: 19100,
    was: null,
    image: IMG.ssd_sata,
    rating: 4.8,
    specs: ["PCIe 4.0", "7300 MB/s", "Heatsink option"],
    stock: "in",
    isNew: false,
  },
  {
    id: "hdd-8tb",
    name: "Barracuda 8TB 3.5 HDD",
    brand: "Seagate",
    category: "Storage",
    price: 8100,
    was: null,
    image: IMG.hdd,
    rating: 4.3,
    specs: ["5400 RPM", "256MB cache", "SATA 6Gb/s"],
    stock: "in",
    isNew: false,
  },
  {
    id: "ssd-p3plus-2tb",
    name: "Crucial P3 Plus 2TB NVMe SSD",
    brand: "Crucial",
    category: "Storage",
    price: 6300,
    was: 7500,
    image: IMG.ssd_nvme,
    rating: 4.5,
    specs: ["PCIe 4.0", "5000 MB/s read", "M.2 2280"],
    stock: "in",
    isNew: false,
  },
  {
    id: "ssd-980-1tb",
    name: "Samsung 980 1TB NVMe SSD",
    brand: "Samsung",
    category: "Storage",
    price: 4600,
    was: 5800,
    image: IMG.ssd_sata,
    rating: 4.6,
    specs: ["PCIe 3.0", "3500 MB/s read", "M.2 2280"],
    stock: "in",
    isNew: false,
  },
  {
    id: "ssd-mp600-4tb",
    name: "Corsair MP600 PRO LPX 4TB",
    brand: "Corsair",
    category: "Storage",
    price: 19100,
    was: null,
    image: IMG.hdd,
    rating: 4.8,
    specs: ["PCIe 4.0", "7100 MB/s", "PS5 compatible"],
    stock: "in",
    isNew: false,
  },
  {
    id: "ssd-t500-1tb",
    name: "Crucial T500 1TB NVMe SSD",
    brand: "Crucial",
    category: "Storage",
    price: 5200,
    was: 6300,
    image: IMG.ssd_nvme,
    rating: 4.7,
    specs: ["PCIe 4.0", "7300 MB/s", "M.2 2280"],
    stock: "in",
    isNew: false,
  },
  {
    id: "hdd-4tb",
    name: "IronWolf 4TB NAS HDD",
    brand: "Seagate",
    category: "Storage",
    price: 5800,
    was: null,
    image: IMG.hdd,
    rating: 4.5,
    specs: ["5900 RPM", "NAS workload", "3.5-inch"],
    stock: "in",
    isNew: false,
  },
  {
    id: "hdd-12tb",
    name: "WD Red Plus 12TB HDD",
    brand: "Western Digital",
    category: "Storage",
    price: 13900,
    was: 15600,
    image: IMG.ssd_sata,
    rating: 4.6,
    specs: ["7200 RPM", "CMR", "NAS-ready"],
    stock: "in",
    isNew: false,
  },
  {
    id: "ssd-sn770-2tb",
    name: "WD Black SN770 2TB",
    brand: "Western Digital",
    category: "Storage",
    price: 7500,
    was: 8700,
    image: IMG.ssd_nvme,
    rating: 4.5,
    specs: ["PCIe 4.0", "5150 MB/s", "M.2 2280"],
    stock: "in",
    isNew: false,
  },
  {
    id: "ssd-870evo-2tb",
    name: "Samsung 870 EVO 2TB SATA SSD",
    brand: "Samsung",
    category: "Storage",
    price: 8700,
    was: null,
    image: IMG.hdd,
    rating: 4.7,
    specs: ["2.5-inch SATA", "560 MB/s", "V-NAND"],
    stock: "in",
    isNew: false,
  },
  {
    id: "ssd-kc3000-2tb",
    name: "Kingston KC3000 2TB NVMe SSD",
    brand: "Kingston",
    category: "Storage",
    price: 9800,
    was: 11600,
    image: IMG.ssd_sata,
    rating: 4.6,
    specs: ["PCIe 4.0", "7000 MB/s", "M.2 2280"],
    stock: "in",
    isNew: false,
  },
  {
    id: "ssd-990pro-4tb",
    name: "990 PRO 4TB NVMe SSD",
    brand: "Samsung",
    category: "Storage",
    price: 20300,
    was: null,
    image: IMG.ssd_nvme,
    rating: 4.9,
    specs: ["PCIe 4.0", "7450 MB/s", "M.2 2280"],
    stock: "low",
    isNew: true,
  },
  {
    id: "ssd-t705-2tb",
    name: "Crucial T705 2TB PCIe 5.0",
    brand: "Crucial",
    category: "Storage",
    price: 17400,
    was: 20300,
    image: IMG.hdd,
    rating: 4.8,
    specs: ["PCIe 5.0", "14500 MB/s", "M.2 2280"],
    stock: "in",
    isNew: true,
  },
  {
    id: "ssd-sn850x-2tb",
    name: "WD Black SN850X 2TB",
    brand: "Western Digital",
    category: "Storage",
    price: 11600,
    was: 13900,
    image: IMG.ssd_sata,
    rating: 4.8,
    specs: ["PCIe 4.0", "7300 MB/s", "M.2 2280"],
    stock: "in",
    isNew: false,
  },
  {
    id: "hdd-20tb",
    name: "Exos X20 20TB Enterprise HDD",
    brand: "Seagate",
    category: "Storage",
    price: 29000,
    was: null,
    image: IMG.ssd_nvme,
    rating: 4.5,
    specs: ["7200 RPM", "SATA 6Gb/s", "Enterprise"],
    stock: "in",
    isNew: false,
  },
  {
    id: "ssd-firecuda-4tb",
    name: "FireCuda 530 4TB NVMe",
    brand: "Seagate",
    category: "Storage",
    price: 23200,
    was: 27800,
    image: IMG.hdd,
    rating: 4.7,
    specs: ["PCIe 4.0", "7300 MB/s", "M.2 2280"],
    stock: "in",
    isNew: false,
  },
  {
    id: "ssd-a2000-1tb",
    name: "A2000 1TB NVMe SSD",
    brand: "Kingston",
    category: "Storage",
    price: 4000,
    was: 5200,
    image: IMG.ssd_sata,
    rating: 4.4,
    specs: ["PCIe 3.0", "2200 MB/s", "M.2 2280"],
    stock: "in",
    isNew: false,
  },
  {
    id: "ssd-p5plus-2tb",
    name: "P5 Plus 2TB NVMe SSD",
    brand: "Crucial",
    category: "Storage",
    price: 9200,
    was: 11000,
    image: IMG.ssd_nvme,
    rating: 4.6,
    specs: ["PCIe 4.0", "6600 MB/s", "M.2 2280"],
    stock: "in",
    isNew: false,
  },
  {
    id: "ssd-980pro-2tb",
    name: "980 PRO 2TB NVMe SSD",
    brand: "Samsung",
    category: "Storage",
    price: 11600,
    was: 13900,
    image: IMG.hdd,
    rating: 4.8,
    specs: ["PCIe 4.0", "7000 MB/s", "M.2 2280"],
    stock: "in",
    isNew: false,
  },

  // ─── PSUs ─────────────────────────────────────────────────────────────────────
  {
    id: "psu-850",
    name: "RM850e 850W Gold Fully Modular",
    brand: "Corsair",
    category: "PSU",
    price: 6900,
    was: 7500,
    image: IMG.psu,
    rating: 4.7,
    specs: ["ATX 3.1", "Cybenetics Gold", "Quiet fan"],
    stock: "in",
    isNew: false,
  },
  {
    id: "psu-1000",
    name: "Straight Power 12 1000W Platinum",
    brand: "be quiet!",
    category: "PSU",
    price: 11000,
    was: null,
    image: IMG.psu,
    rating: 4.8,
    specs: ["ATX 3.0", "Dual 12VHPWR", "Silent Wings fan"],
    stock: "in",
    isNew: false,
  },
  {
    id: "psu-650",
    name: "CX650M 650W Bronze",
    brand: "Corsair",
    category: "PSU",
    price: 4000,
    was: 4600,
    image: IMG.psu,
    rating: 4.3,
    specs: ["Semi-modular", "80+ Bronze", "120mm fan"],
    stock: "in",
    isNew: false,
  },
  {
    id: "psu-1200",
    name: "HX1200i 1200W Platinum",
    brand: "Corsair",
    category: "PSU",
    price: 17400,
    was: null,
    image: IMG.psu,
    rating: 4.8,
    specs: ["Fully modular", "ATX 3.0", "80+ Platinum"],
    stock: "in",
    isNew: false,
  },
  {
    id: "psu-850-platinum",
    name: "SuperNOVA 850 P6",
    brand: "EVGA",
    category: "PSU",
    price: 9800,
    was: 11000,
    image: IMG.psu,
    rating: 4.6,
    specs: ["Fully modular", "80+ Platinum", "ATX"],
    stock: "out",
    isNew: false,
  },
  {
    id: "psu-1000-gold",
    name: "Toughpower GF A3 1000W Gold",
    brand: "Thermaltake",
    category: "PSU",
    price: 9200,
    was: null,
    image: IMG.psu,
    rating: 4.5,
    specs: ["ATX 3.0", "Fully modular", "Native 12VHPWR"],
    stock: "in",
    isNew: false,
  },
  {
    id: "psu-550",
    name: "Pure Power 12 M 550W",
    brand: "be quiet!",
    category: "PSU",
    price: 5200,
    was: 5800,
    image: IMG.psu,
    rating: 4.4,
    specs: ["80+ Gold", "ATX 3.0", "Quiet operation"],
    stock: "in",
    isNew: false,
  },
  {
    id: "psu-750",
    name: "Focus GX-750 750W Gold",
    brand: "Seasonic",
    category: "PSU",
    price: 6300,
    was: null,
    image: IMG.psu,
    rating: 4.7,
    specs: ["ATX 3.0", "Fully modular", "10-year warranty"],
    stock: "in",
    isNew: false,
  },
  {
    id: "psu-1600",
    name: "AX1600i 1600W Titanium",
    brand: "Corsair",
    category: "PSU",
    price: 40600,
    was: null,
    image: IMG.psu,
    rating: 4.9,
    specs: ["Fully modular", "80+ Titanium", "Digital control"],
    stock: "low",
    isNew: true,
  },
  {
    id: "psu-1000-titanium",
    name: "Prime TX-1000 1000W Titanium",
    brand: "Seasonic",
    category: "PSU",
    price: 23200,
    was: 27800,
    image: IMG.psu,
    rating: 4.8,
    specs: ["Fully modular", "80+ Titanium", "ATX 3.0"],
    stock: "in",
    isNew: true,
  },

  // ─── Cases ────────────────────────────────────────────────────────────────────
  {
    id: "case-4000d",
    name: "4000D Airflow Mid Tower",
    brand: "Corsair",
    category: "Case",
    price: 6000,
    was: null,
    image: IMG.case_glass,
    rating: 4.8,
    specs: ["Tempered glass", "High airflow front", "USB-C"],
    stock: "in",
    isNew: false,
  },
  {
    id: "case-o11",
    name: "O11 Dynamic EVO XL",
    brand: "Lian Li",
    category: "Case",
    price: 13600,
    was: 15000,
    image: IMG.case_mesh,
    rating: 4.7,
    specs: ["Full tower", "Dual chamber", "RGB optional"],
    stock: "in",
    isNew: false,
  },
  {
    id: "case-north",
    name: "North Mid Tower",
    brand: "Fractal Design",
    category: "Case",
    price: 8100,
    was: 8700,
    image: IMG.case_rgb,
    rating: 4.8,
    specs: ["Wood front panel", "High airflow", "ATX support"],
    stock: "in",
    isNew: false,
  },
  {
    id: "case-5000d",
    name: "5000D Airflow",
    brand: "Corsair",
    category: "Case",
    price: 9500,
    was: 10400,
    image: IMG.case_glass,
    rating: 4.7,
    specs: ["ATX", "High airflow", "Cable management channel"],
    stock: "in",
    isNew: false,
  },
  {
    id: "case-h9",
    name: "H9 Flow",
    brand: "NZXT",
    category: "Case",
    price: 9200,
    was: null,
    image: IMG.case_mesh,
    rating: 4.6,
    specs: ["Dual chamber", "Panoramic glass", "ATX"],
    stock: "in",
    isNew: false,
  },
  {
    id: "case-lancool216",
    name: "LANCOOL 216",
    brand: "Lian Li",
    category: "Case",
    price: 6300,
    was: 6900,
    image: IMG.case_rgb,
    rating: 4.6,
    specs: ["160mm front fans", "Mesh front", "ATX"],
    stock: "in",
    isNew: false,
  },
  {
    id: "case-popair",
    name: "Pop Air RGB",
    brand: "Fractal Design",
    category: "Case",
    price: 5800,
    was: null,
    image: IMG.case_glass,
    rating: 4.4,
    specs: ["Mesh panel", "Tempered glass", "ATX"],
    stock: "in",
    isNew: false,
  },
  {
    id: "case-meshify2",
    name: "Meshify 2 Compact",
    brand: "Fractal Design",
    category: "Case",
    price: 8100,
    was: 8700,
    image: IMG.case_mesh,
    rating: 4.7,
    specs: ["Airflow layout", "Nexus fan hub", "ATX"],
    stock: "in",
    isNew: false,
  },
  {
    id: "case-o11d-evo",
    name: "O11D EVO RGB",
    brand: "Lian Li",
    category: "Case",
    price: 11600,
    was: 13900,
    image: IMG.case_rgb,
    rating: 4.8,
    specs: ["Dual chamber", "Tempered glass", "E-ATX"],
    stock: "in",
    isNew: true,
  },
  {
    id: "case-h7",
    name: "H7 Flow",
    brand: "NZXT",
    category: "Case",
    price: 8700,
    was: null,
    image: IMG.case_glass,
    rating: 4.6,
    specs: ["Mesh front", "Tempered glass", "ATX"],
    stock: "low",
    isNew: true,
  },

  // ─── Cooling ──────────────────────────────────────────────────────────────────
  {
    id: "cool-aio",
    name: "Kraken 360 RGB AIO",
    brand: "NZXT",
    category: "Cooling",
    price: 10400,
    was: null,
    image: IMG.cool_aio,
    rating: 4.6,
    specs: ["360mm radiator", "LCD pump cap option", "AM5/LGA1700"],
    stock: "in",
    isNew: false,
  },
  {
    id: "cool-air",
    name: "NH-D15 chromax.black",
    brand: "Noctua",
    category: "Cooling",
    price: 6900,
    was: null,
    image: IMG.cool_air,
    rating: 4.9,
    specs: ["Dual tower", "140mm fans", "Quiet"],
    stock: "in",
    isNew: false,
  },
  {
    id: "cool-ak620",
    name: "AK620 Zero Dark",
    brand: "DeepCool",
    category: "Cooling",
    price: 4000,
    was: null,
    image: IMG.cool_fan,
    rating: 4.6,
    specs: ["Dual tower", "120mm fans", "AM5/LGA1700"],
    stock: "in",
    isNew: false,
  },
  {
    id: "cool-ls720",
    name: "LS720 360mm AIO",
    brand: "DeepCool",
    category: "Cooling",
    price: 6900,
    was: null,
    image: IMG.cool_aio,
    rating: 4.5,
    specs: ["360mm radiator", "ARGB", "AM5/LGA1700"],
    stock: "in",
    isNew: false,
  },
  {
    id: "cool-pa120",
    name: "Peerless Assassin 120 SE",
    brand: "Thermalright",
    category: "Cooling",
    price: 2300,
    was: 2900,
    image: IMG.cool_air,
    rating: 4.8,
    specs: ["Dual tower", "Excellent value", "120mm fans"],
    stock: "in",
    isNew: false,
  },
  {
    id: "cool-fuma3",
    name: "Fuma 3 Air Cooler",
    brand: "Scythe",
    category: "Cooling",
    price: 2900,
    was: null,
    image: IMG.cool_fan,
    rating: 4.6,
    specs: ["Offset dual tower", "Quiet fans", "RAM clearance"],
    stock: "in",
    isNew: false,
  },
  {
    id: "cool-arctic360",
    name: "Liquid Freezer III 360",
    brand: "Arctic",
    category: "Cooling",
    price: 7500,
    was: 8700,
    image: IMG.cool_aio,
    rating: 4.8,
    specs: ["Thick radiator", "VRM fan", "AM5/LGA1700"],
    stock: "in",
    isNew: false,
  },
  {
    id: "cool-kraken-elite",
    name: "Kraken Elite 360 RGB",
    brand: "NZXT",
    category: "Cooling",
    price: 17400,
    was: 20300,
    image: IMG.cool_aio,
    rating: 4.7,
    specs: ["360mm", "2.36in LCD", "AM5/LGA1700"],
    stock: "in",
    isNew: true,
  },
  {
    id: "cool-nh-u12a",
    name: "NH-U12A chromax.black",
    brand: "Noctua",
    category: "Cooling",
    price: 5200,
    was: null,
    image: IMG.cool_air,
    rating: 4.8,
    specs: ["Single tower", "120mm fans", "Low-profile"],
    stock: "in",
    isNew: false,
  },
  {
    id: "cool-be-silent",
    name: "Dark Rock Pro 5",
    brand: "be quiet!",
    category: "Cooling",
    price: 8100,
    was: 9200,
    image: IMG.cool_air,
    rating: 4.7,
    specs: ["Dual tower", "135mm fan", "Silent Wings 4"],
    stock: "low",
    isNew: true,
  },
];
